<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="methods" name="Test(failed)">
    <classes>
      <class name="testcases.HomePagetest">
        <methods>
          <include name="verify_product_features_presence"/>
          <include name="close"/>
          <include name="verifytitle_on_hompage"/>
          <include name="startup"/>
          <include name="verifylogo_on_homepage"/>
          <include name="verify_allmenuitems_on_homepage"/>
        </methods>
      </class> <!-- testcases.HomePagetest -->
      <class name="testcases.Logintest">
        <methods>
          <include name="close"/>
          <include name="startup"/>
          <include name="LoginWith_Valid_Credentials" invocation-numbers="0"/>
        </methods>
      </class> <!-- testcases.Logintest -->
      <class name="testcases.Signuptest">
        <methods>
          <include name="close"/>
          <include name="signup"/>
          <include name="startup"/>
        </methods>
      </class> <!-- testcases.Signuptest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
